### ISSUE TITLE
Add SLS (Log Service) table.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-alicloud#119]
Some of the CIS requirement depends on this SLS service 

2.3 Ensure audit logs for multiple cloud resources are integrated with Log Service (Manual)

(More details will be added soon)

**Comment by bigdatasourav** [comment]
Explored the service in alicloud , unable to find the required API.

https://github.com/aliyun/alibaba-cloud-sdk-go/tree/master/services/sls

https://api.alibabacloud.com/?spm=5176.2020520112.top-nav.14.1e1214das4PD1K#/?product=Sddp&version=2019-01-03&api=DescribeOriginalLogs&params={}&tab=DEMO&lang=GO

https://partners-intl.aliyun.com/help/doc-detail/29018.htm?spm=a2c63.p38356.a1.5.224c2610GtI0FO

As discussed, put it on hold as of now.
