### ISSUE TITLE
Message: The input parameter "SecurityToken" that is mandatory for processing this request is not supplied. (SQLSTATE HV000)

### ISSUE THREAD

**Issue by zhujian0805** [turbot/steampipe-plugin-alicloud#291]
**Describe the bug**
steampipe@hostname ~$ steampipe query
Welcome to Steampipe v0.16.1
For more information, type .help
> select * from alicloud_vpc
Error: SDK.ServerError
ErrorCode: MissingParameter
Recommend: https://next.api.aliyun.com/troubleshoot?q=MissingParameter&product=Vpc
RequestId: FADE5107-8909-594E-A28E-7384395ADC25
Message: The input parameter "SecurityToken" that is mandatory for processing this request is not supplied. (SQLSTATE HV000)

**Steampipe version (`steampipe -v`)**
steampipe version 0.16.1

**Plugin version (`steampipe plugin list`)**
steampipe plugin list
+-------------------------------------------------+---------+-------------+
| Name                                            | Version | Connections |
+-------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/alicloud@latest | 0.9.0   | alicloud    |
+-------------------------------------------------+---------+-------------+

**To reproduce**
> select * from alicloud_vpc
Error: SDK.ServerError
ErrorCode: MissingParameter
Recommend: https://next.api.aliyun.com/troubleshoot?q=MissingParameter&product=Vpc
RequestId: FADE5107-8909-594E-A28E-7384395ADC25
Message: The input parameter "SecurityToken" that is mandatory for processing this request is not supplied. (SQLSTATE HV000)

**Comment by zhujian0805** [comment]
Also can this plugin support profile, similar to the aws plugin?

**Comment by rajlearner17** [comment]
@zhujian0805 appreciate trying out Steampipe! Thank you for your feedback.

I cannot reproduce with the following versions; I am using  access_key  &  secret_key in `alicloud.spc`, which works fine.

plugin as ` hub.steampipe.io/plugins/turbot/alicloud@latest        | 0.9.0   | alicloud ` with  `Steampipe v0.16.1`

![image](https://user-images.githubusercontent.com/26873346/189303242-9d28a90f-80df-429b-8cf9-e13eaf356bc0.png)

I would suggest rechecking the credentials once to confirm it's valid and confirm us?

For the time being, we are supporting these [authentications](https://hub.steampipe.io/plugins/turbot/alicloud)

**Comment by zhujian0805** [comment]
hi @rajlearner17  thanks for your reply.

In my setup, i use cloud sso, so it provides a SECURITY_TOKEN for authentication, can we add the SECURITY TOKEN support as well? I think this is super useful in multi-account setup.

```
export ALIBABACLOUD_ACCESS_KEY_ID=STS.************
export ALIBABACLOUD_ACCESS_KEY_SECRET=27P9x************
export SECURITY_TOKEN=CAI*******
```

**Comment by zhujian0805** [comment]
hi

**Comment by cbruno10** [comment]
Hi @zhujian0805 , sorry for the silence on this!

We haven't had an opportunity to work on this yet, so I've just attached a `help wanted` label in hopes that another plugin user will take interest in this request and find time to work on it.
