### ISSUE TITLE
Add table `alicloud_vpc_ipv4_gateway`

### ISSUE THREAD

**Issue by karanpopat** [turbot/steampipe-plugin-alicloud#305]
**References**
API - https://pkg.go.dev/github.com/aliyun/alibaba-cloud-sdk-go@v1.62.108/services/vpc#Client.ListIpv4Gateways

**Comment by ParthaI** [comment]
In our plugin we are using the Alicloud GO SDK version `v1.61.1140` this version does not support this API call. We need to update our SDK version first to add this table in.
