### ISSUE TITLE
Querying `alicloud_cs_kubernetes_cluster` table result in error when no ACK present

### ISSUE THREAD

**Issue by vmdude** [turbot/steampipe-plugin-alicloud#338]
**Describe the bug**
Querying the `alicloud_cs_kubernetes_cluster` table require the [AliyunCSDefaultRole](https://www.alibabacloud.com/help/en/container-service-for-kubernetes/latest/ack-default-roles#section-xlt-fbw-1fd) RAM system role to exist, which is created upon first ACK cluster creation.
When you query on an account that doesn't have this role, the query fail with the following error:
```plain
Error: SDK.ServerError
ErrorCode:
Recommend:
RequestId:
Message: {"code":"400","message":"Aliyun API Error: RequestId: XXX Status Code: 404 Code: EntityNotExist.Role Message: The role not exists: acs:ram::XXX:role/aliyuncsdefaultrole. ","requestId":"XXX","status":400}
```
Alicloud steampipe plugin does not seems to support the `ignore_code_errors` settings in connections like AWS/GCP plugin, thus query will always `exit 1` making it difficult to properly execute it automatically.

**Steampipe version (`steampipe -v`)**
```plain
steampipe --version
Steampipe v0.19.1
```

**Plugin version (`steampipe plugin list`)**
```plain
steampipe plugin list
hub.steampipe.io/plugins/turbot/alicloud@latest = 0.14.0
```

**To reproduce**
Configure an Alicloud profile to an account where no ACK cluster has ever been configured.
Run the following query:
```sql
select
  *
from
  alicloud_cs_kubernetes_cluster;
```

**Expected behavior**
Check if needed role is available before using the API call, or having the possibility to ignore these errors like in GCP plugin.

**Comment by misraved** [comment]
Thanks @vmdude for raising the bug 👍.

We will take a look at it and post our feedback on this thread 👍.

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-alicloud/pull/344
