### ISSUE TITLE
Alibaba plugin support for profile connection

### ISSUE THREAD

**Issue by jzhuuuu** [turbot/steampipe-plugin-alicloud#405]
**Is your feature request related to a problem? Please describe.**

add support for alibaba plugin support multi-account connection configuration with profile(similar to AWS)? 

currently if there are many alibaba accounts, you have to add them all and have separate aksk for each of them.

instead of add aksk for each connection, add a aksk for the main account and add the profile for the other sub-account. just like AWS plugin's profile connection configuration

**Describe the solution you'd like**
similar to AWS profile connection configuration

**Comment by jzhuuuu** [comment]
hi team, are we going to have an estimate about when this feature will be added?

**Comment by ParthaI** [comment]
Hello @jzhuuuu, we are currently working on it. Will update you once it is over. Thanks!

**Comment by ParthaI** [comment]
Hi @jzhuuuu,

I have initiated a [draft PR](https://github.com/turbot/steampipe-plugin-alicloud/pull/409) to address this issue.

### Overview of Changes
- **Consistent Table Functionality**: The functionality of the table remains unchanged.
- **Enhanced Profile Support**: We've introduced support for profile configurations within the Steampipe connection config.
- **Expanded Authentication Methods**: We now support multiple authentication methods for profiles, detailed in the table below:

| Profile          | Credential                                           | Status | Region     | Language |
|------------------|------------------------------------------------------|--------|------------|----------|
| default          | AK: ***t1u                                           | Valid  | ap-south-1 | en       |
| ramRoleArn       | RamRoleArn: ***g3D                                   | Valid  | cn-hangzhou| en       |
| stsTokenProfile* | StsToken: ***KpC                                     | Valid  | cn-hangzhou| en       |
| ecsRole          | EcsRamRole: acs:ram::************:role/ecs-trust     | Valid  | cn-hangzhou| en       |

- **Configuration Example**: Configure the profile in the `alicloud.spc` file as follows:
  ```hcl
  connection "alicloud" {
    plugin  = "alicloud"
    profile = "stsTokenProfile"
  }
  ```

It would be great if you want to test these changes on the PR branch (`issue-405`) and share your feedback.

### Steps to Build the Plugin Locally
Follow these steps to build the plugin with the code changes from the PR branch:
- Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-alicloud.git`
- Navigate to the project directory: `cd steampipe-plugin-alicloud`
- Switch to the target branch: `git checkout issue-405`
- Build the plugin: Run the command `make`
- Execute queries to test the functionality.

Thank you!

**Comment by zhujian0805** [comment]
Thanks! will start to test it.

**Comment by zhujian0805** [comment]
hi @ParthaI, I followed the instruction and got this error:
`> select * from cf.alicloud_vpc;

Error: cf: unsupported authentication mode 'ChainableRamRoleArn' (SQLSTATE HV000)

+------+-----+--------+--------+---------------+------------+-----------------+------------+-------------+------------+-----------------+-------------------+------------+----------+--------------------------+-------------------+---------------------+-------------------------+----->
| name | arn | vpc_id | status | creation_time | cidr_block | ipv6_cidr_block | vrouter_id | description | is_default | network_acl_num | resource_group_id | cen_status | owner_id | support_advanced_feature | advanced_resource | dhcp_options_set_id | dhcp_options_set_status | asso>
+------+-----+--------+--------+---------------+------------+-----------------+------------+-------------+------------+-----------------+-------------------+------------+----------+--------------------------+-------------------+---------------------+-------------------------+----->
+------+-----+--------+--------+---------------+------------+-----------------+------------+-------------+------------+-----------------+-------------------+------------+----------+--------------------------+-------------------+---------------------+-------------------------+----->
`

**Comment by zhujian0805** [comment]
aliyun cli works as expected

**Comment by ParthaI** [comment]
@zhujian0805, originally, our main objective was to incorporate support for various profile modes such as:
- AK
- RamRoleArn
- EcsRamRole
- StsToken

However, I've now made additional updates to the same branch `issue-405` to include support for the `ChainableRamRoleArn` profile mode.

Could you please pull the latest changes from the `issue-405` branch into your local environment, build the plugin locally, and re-run the query?

Thanks!

**Comment by zhujian0805** [comment]
@ParthaI I have tested and confirm it work as expected. Thanks so much.

can you cut a release for it?

**Comment by ParthaI** [comment]
Thank you @zhujian0805 for your confirmation. This PR is currently undergoing the review process. I will consult with the team regarding the next steps afterward.

**Comment by zhujian0805** [comment]
@ParthaI any updates on this?

**Comment by ParthaI** [comment]
Hi @zhujian0805, sorry, it is still under review. It may be released early next week. Thanks!
